# Generated by Django 3.0.1 on 2019-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
    ]
